### ISSUE TITLE
Uncaught exception - std@sys_read_dir

### ISSUE THREAD

**Issue by OnionKidFF3** [YAL-GameMaker-Tools/GMVitalizer#3]
Trying to convert a 2.2.5 project results in this:

Loading project... OK! (1407ms)
Printing...
src/vit/VitProjectOptions.hx:23: No config available, copying default
Indexing... OK! (4125ms)
Called from ? line 1
Called from GMVitalizer.hx line 35
Called from GMVitalizer.hx line 23
Called from VitProject.hx line 484
Called from VitProject.hx line 250
Called from Ruleset.hx line 279
Called from Ruleset.hx line 207
Called from C:\Tools\Dev\HaxeToolkit\haxe\std/neko/_std/sys/FileSystem.hx line 95
Uncaught exception - std@sys_read_dir

**Comment by YellowAfterlife** [comment]
That sounds like a kind of thing that would happen if you didn't unzip GMVitalizer before running it, or maybe if you ran it from a different work directory than where compatibility.gmx sits. Would you like to elaborate the exact steps that you've done?

**Comment by OnionKidFF3** [comment]
So am I supposed to place GMVitalizer INSIDE the compatibility.gmx folder? Because that folder is NEXT to GMVitalizer (in the same directory). And yes, the entire program is unzipped. I tried storing it in both Program Files and in Documents, didn't resolve the issue.

**Comment by YellowAfterlife** [comment]
No, you're expected to drag your YYP onto gmvitalizer.exe, like this:

![image](https://github.com/YAL-GameMaker-Tools/GMVitalizer/assets/731492/de4fa668-e769-494a-a718-6fe6bb553f52)

**Comment by OnionKidFF3** [comment]
I tried that, the GMVitalizer window appeared for a split second, then disappeared. So I dragged gmvitalizer.exe onto CMD, then pressed space, then dragged the YYP, then space again, then specified the output directory. It's the only thing that got me anywhere.

**Comment by YellowAfterlife** [comment]
Oh right, this needs an output directory too - I mixed it up with another tool of mine, which is kind of funny since there's a README here describing what to do.

This isn't the most newbie-friendly tool of mine but also it's perhaps it's among the more exotic ones, especially with the limited range of GameMaker versions that it could realistically support.

**Comment by OnionKidFF3** [comment]
So you don't know how to solve it?

**Comment by YellowAfterlife** [comment]
Based on
> It's the only thing that got me anywhere.

I thought that did work for you.

As long as you open a Command Prompt or a Powershell window in the same directory as GMVitalizer executable, should be fine

**Comment by OnionKidFF3** [comment]
I managed to get it to work but there's no compatibility script or replacement of any sort for matrix_transform_vertex.

**Comment by YellowAfterlife** [comment]
If it's just
```
matrix_transform_vertex(matrix_get(matrix_world), X, Y, Z)
```
that would be `d3d_transform_vertex(X, Y, Z)`.

Otherwise you'd have to implement it yourself (see [HTML5 runtime code](https://github.com/YoYoGames/GameMaker-HTML5/blob/a05703e99c2218cae2e54ad94cdb1997f3a5417e/scripts/functions/Function_D3D.js#L1815-L1836) for reference).

Generally there are only compatibility scripts for functions that appeared in the projects that this tool was made for, but if you add new scripts to Compatibilty.gmx project, GMVitalizer will automatically use them for same-named functions next time you run it.

---

So what were you doing before that made GMVitalizer not work?

**Comment by OnionKidFF3** [comment]
It's just that the guide that you provided was vague and confusing. The exact steps are right-clicking inside the GMVitalizer folder while holding Shift, then selecting "Open PowerShell window here", and then once PowerShell loads you type in .\GMVitalizer as well as the filepaths to both the YYP and the output, both in quotations. Then you press Enter and it Just Works™.

Also you should do something about GMS2's new camera functions since that's not a thing GMS1 and GMVitalizer doesn't know what to do with them either.

**Comment by YellowAfterlife** [comment]
> Also you should do something about GMS2's new camera functions since that's not a thing GMS1 and GMVitalizer doesn't know what to do with them either.

I perhaps could carve out a weekend for it if someone paid for my time, but I don't think there's an elegant way to map GMS2 camera functions to GMS1 - the API is broader, you can pass cameras around, and you can set matrices. A GM:S implementation would need a controller object and a bunch of hacks.

**Comment by OnionKidFF3** [comment]
I see, guess trying to backport Snidr's 3D collisions system to GMS1 is a fool's errand.
